# Generated by Django 2.2.5 on 2021-01-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_newapp', '0002_bookinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
