# Generated by Django 2.2.5 on 2021-01-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_newapp', '0003_auto_20210121_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={},
        ),
        migrations.CreateModel(
            name='Peopleinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'female'), (1, 'male')], default=0)),
                ('description', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_newapp.Bookinfo')),
            ],
            options={
                'db_table': 'peopleinfo',
            },
        ),
    ]
